[package]
name = "feffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ndarray = "0.15.6"
rand_chacha = "0.3.1"
rayon = "1.6.1"
parking_lot = "0.12.1"