[package]
name = "feffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ndarray = "0.15.6"
rand_chacha = "0.3.1"
threadpool = "1.8.1"
num_cpus = "1.15.0"